# ---------- main ----------
[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "root" 
joints = "root"

# ---------- sling ----------
[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "slingParent" 
joints = "slingRibbonOffsetParent_jnt"
use_joint_names = true

# ----------
[[rig_module]]
rig_module = "flexi_surface_fk_ctrl_mod" 
rig_module_name = "slingFlexi" 
joints = "slingMain_01_jnt"
get_joint_chain = true
flexi_surface = "flexiSurfaceSling_geo"
hide_end_ctrl = true

[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "sling" 
joints = "slingRibbonOffset_start_01_jnt"
get_joint_chain = true
use_joint_names = true
hide_scale = true

# ----------
[[rig_module]]
rig_module = "flexi_surface_fk_ctrl_mod" 
rig_module_name = "slingLoop" 
joints = "slingTop_01_jnt"
get_joint_chain = true
flexi_surface = "flexiSurfaceSlingLoop_geo"
hide_end_ctrl = true

[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "slingLoop" 
joints = "slingLoopRibbonOffset_01_jnt"
get_joint_chain = true
use_joint_names = true
hide_scale = true

# ---------- sling rock ----------
[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "slingRock" 
joints = "slingRock_jnt"
display_layer = true
