rig_name = "puppet" # name string used for top rig and skeletal mesh groups
unreal_rig = true  # sets skeletal mesh group rotate "x" to -90

[[rig_module]]
rig_module = "world_control_mod" 
rig_module_name = "world" 

[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "global" 
joints = "root"
constraint = false

[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "root" 
joints = "root"

[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "cog" 
joints = "cog_loc"
constraint = false

[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "pelvis" 
joints = "pelvis"

[[rig_module]]
rig_module = "fk_chain_mod" 
rig_module_name = "spine" 
joints = "spine_01, spine_02, spine_03, spine_04"

[[rig_module]]
rig_module = "fk_chain_mod" 
rig_module_name = "neck" 
joints = "neck_01, neck_02, head"

[[rig_module]]
rig_module = "biped_leg_mod" 
rig_module_name = "leg" 
mirror_direction = "left" 
joints = "thigh_l, calf_l, foot_l, ball_l" 
upper_twist_joints = "thigh_twist_01_l, thigh_twist_02_l" 
lower_twist_joints = "calf_twist_02_l, calf_twist_01_l"
mirror_right = true

[[rig_module]]
rig_module = "fk_ik_single_chain_mod" 
rig_module_name = "shoulder" 
mirror_direction = "left" 
joints = "clavicle_l, upperarm_l" 
mirror_right = true

[[rig_module]]
rig_module = "biped_limb_mod" 
rig_module_name = "arm" 
mirror_direction = "left" 
joints = "upperarm_l, lowerarm_l, hand_l" 
upper_twist_joints = "upperarm_twist_01_l, upperarm_twist_02_l" 
lower_twist_joints = "lowerarm_twist_02_l, lowerarm_twist_01_l"
mirror_right = true

# --------------- fingers ---------------
[[rig_module]]
rig_module = "fk_chain_mod" 
rig_module_name = "thumb" 
mirror_direction = "left"
joints = "thumb_01_l, thumb_02_l, thumb_03_l"
mirror_right = true

[[rig_module]]
rig_module = "fk_chain_mod" 
rig_module_name = "indexFinger"
mirror_direction = "left" 
joints = "index_metacarpal_l, index_01_l, index_02_l, index_03_l"
mirror_right = true

[[rig_module]]
rig_module = "fk_chain_mod" 
rig_module_name = "middleFinger"
mirror_direction = "left" 
joints = "middle_metacarpal_l, middle_01_l, middle_02_l, middle_03_l"
mirror_right = true

[[rig_module]]
rig_module = "fk_chain_mod" 
rig_module_name = "ringFinger" 
mirror_direction = "left" 
joints = "ring_metacarpal_l, ring_01_l, ring_02_l, ring_03_l"
mirror_right = true

[[rig_module]]
rig_module = "fk_chain_mod" 
rig_module_name = "pinkFinger" 
mirror_direction = "left" 
joints = "pinky_metacarpal_l, pinky_01_l, pinky_02_l, pinky_03_l"
mirror_right = true
