[[control]]
control = "global_ctrl"
parents = "world_ctrl"

[[control]]
control = "root_ctrl"
parents = "global_ctrl"

[[control]]
control = "cog_ctrl"
parents = "root_ctrl"

[[control]]
control = "pelvis_ctrl"
parents = "cog_ctrl, root_ctrl, global_ctrl, world_ctrl"

[[control]]
control = "spine_01_ctrl"
parents = "pelvis_ctrl, cog_ctrl, root_ctrl, global_ctrl, world_ctrl"
separate_transforms = true
skip_translate = true
skip_scale = true
base_parent = "pelvis_ctrl"

[[control]]
control = "neck_01_ctrl"
parents = "spine_05, pelvis_ctrl, cog_ctrl, root_ctrl, global_ctrl, world_ctrl"
separate_transforms = true
skip_translate = true
skip_scale = true
base_parent = "spine_05"

[[control]]
control = "ikUpperLeg_left_ctrl"
parents = "pelvis_ctrl"
mirror_right = true

[[control]]
control = "fkUpperLeg_left_ctrl"
parents = "pelvis_ctrl, cog_ctrl, root_ctrl, global_ctrl, world_ctrl" 
separate_transforms = true
skip_translate = true
skip_scale = true
base_parent = "pelvis_ctrl"
mirror_right = true

[[control]]
control = "ikLegPoleVector_left_ctrl"
parents = "cog_ctrl, root_ctrl, global_ctrl, world_ctrl, pelvis_ctrl, ikAnkle_left_ctrl"
separate_transforms = true
skip_rotate = true
skip_scale = true
use_point_constraint = true
base_parent = "cog_ctrl, root_ctrl, global_ctrl, world_ctrl"
mirror_right = true

[[control]]
control = "ikAnkle_left_ctrl"
parents = "cog_ctrl, root_ctrl, global_ctrl, world_ctrl, pelvis_ctrl, ikUpperLeg_left_ctrl"
mirror_right = true

[[control]]
control = "fkShoulder_left_01_ctrl"
parents = "spine_05"
mirror_right = true

[[control]]
control = "ikShoulderStart_left_ctrl"
parents = "spine_05"
mirror_right = true

[[control]]
control = "ikUpperArm_left_ctrl"
parents = "offsetShoulder_left_02_jnt"
mirror_right = true

[[control]]
control = "fkUpperArm_left_ctrl"
parents = "offsetShoulder_left_02_jnt, spine_04_ctrl, pelvis_ctrl, cog_ctrl, root_ctrl, global_ctrl, world_ctrl"
separate_transforms = true
skip_translate = true
skip_scale = true
base_parent = "offsetShoulder_left_02_jnt"
mirror_right = true

[[control]]
control = "ikArmPoleVector_left_ctrl"
parents = "cog_ctrl, root_ctrl, global_ctrl, world_ctrl, pelvis_ctrl, spine_04_ctrl, ikEndArm_left_ctrl"
mirror_right = true

[[control]]
control = "ikEndArm_left_ctrl"
parents = "cog_ctrl, root_ctrl, global_ctrl, world_ctrl, pelvis_ctrl, spine_04_ctrl"
mirror_right = true

# --------------- fingers ---------------
[[control]]
control = "thumb_left_01_ctrl"
parents = "hand_l"
mirror_right = true

[[control]]
control = "indexFinger_left_01_ctrl"
parents = "hand_l"
mirror_right = true

[[control]]
control = "middleFinger_left_01_ctrl"
parents = "hand_l"
mirror_right = true

[[control]]
control = "ringFinger_left_01_ctrl"
parents = "hand_l"
mirror_right = true

[[control]]
control = "pinkFinger_left_01_ctrl"
parents = "hand_l"
mirror_right = true

# --------------- switch controls ---------------
[[control]]
control = "legSwch_left_ctrl"
parents = "global_ctrl, root_ctrl, cog_ctrl, pelvis_ctrl, world_ctrl"
mirror_right = true

[[control]]
control = "armSwch_left_ctrl"
parents = "global_ctrl, root_ctrl, cog_ctrl, pelvis_ctrl, world_ctrl"
mirror_right = true

[[control]]
control = "shoulderSwch_left_ctrl"
parents = "global_ctrl, root_ctrl, cog_ctrl, pelvis_ctrl, world_ctrl"
mirror_right = true