# fk_control_blend_mod: Uses fk_control_mod. Blend a single fk control
#   between two joints via blend attribute. Useful for lip corner controls.
#   Don't need parent spacing. Already parented via blend joints.

# lips corner
[[rig_module]]
rig_module = "fk_control_blend_mod" 
rig_module_name = "cornerLips" 
mirror_direction = "left" 
joints = "lips_topOuterLeft_jnt, lips_botOuterLeft_jnt"
blend_joints = "head, jaw_jnt" # requires exactly two joints
use_joint_names = true
mirror_right = true
