# Setup custom rig parent spaces for its rig modules. 
# Also, set up default parent or single parent space when no parent spaces needed.
# Use a single control name for each child control and other control or object names for parents.
#
# Keys:
    # control (str): Child contrl to set up parent spaces for.
    # parents (str): Parent objects. Usually other controls but may be any Maya transform. 
    # separate_transforms (bool): Create seperate attributes for translate, rotate, and scale.
    # default_parent (str): Parent and scale constrain the default parent group, above the parent switch group. 
        # May be used instead of a single "parents" object for a regular parent relationship. 
        # Also, used when a point constraint needs full rotate parent constraint above, like for "use_point_constraint".
    # mirror_right (str): Use left control data for the right side.
    # use_point_constraint (bool): Use point constraint instead of parent translateconstraint. Requires "default_parent". 
    # skip_translate, skip_rotate, skip_scale (bool): Skip translate (or point), rotate or scale parent switch setup. 
        # Requires "separate_transforms" and "default_parent". 
        # False value is the same as not including the arg, so the transform won't be skipped.
        # Skip only works for translate and rotate if separate_transforms is on.
        # Skip scale does work for regular "parents" if "default_parent" value is also given.
# Example:
    # [[control]]
    # control = "ikLegPoleVector_left_ctrl"
    # parents = "root_ctrl, pelvis_ctrl, ikAnkle_left_ctrl"
    # separate_transforms = true
    # skip_translate = false
    # skip_rotate = true
    # skip_scale = true
    # use_point_constraint = true
    # default_parent = "root_ctrl"
    # mirror_right = true

[[control]]
control = "pelvis_ctrl"
parents = "root_ctrl"

[[control]]
control = "ikUpperLeg_left_ctrl"
parents = "pelvis_ctrl"
mirror_right = true

[[control]]
control = "fkUpperLeg_left_ctrl"
parents = "pelvis_ctrl, root_ctrl" 
separate_transforms = true
mirror_right = true

[[control]]
control = "ikLegPoleVector_left_ctrl"
parents = "root_ctrl, pelvis_ctrl, ikAnkle_left_ctrl"
separate_transforms = true
skip_rotate = true
skip_scale = true
use_point_constraint = true
default_parent = "root_ctrl"
mirror_right = true

[[control]]
control = "ikAnkle_left_ctrl"
parents = "root_ctrl, pelvis_ctrl, ikUpperLeg_left_ctrl"
mirror_right = true
