# Connect pre-made ctrls to blendshapes via set driven keys.
# Ctrls would be saved in the "rig_helpers.ma" file.
#
# - Blendshape start and end will be 0 and 1 unless specified.
#   - blendshape_start = 0.0, blendshape_end = 1.0
# - Transform curve start and end will be 0 and 1 unless specified.
#   - curve_start = 0.0, crv_end = 1.0

# blendshape_objs = """
# bodyOriginal_lowGeo,
# eye_lowGeo,
# eyeGlass_lowGeo,
# tongue_lowGeo,
# teeth_lowGeo
# """

inTangentType="linear"
outTangentType="linear"

[[setdrivenkeys]]
blendshape_attr = "noseSneerLeft"
transform_crv = "noseSneerLeft_ctrl"
crv_attr = "translateY"
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "noseSneerLeft"
transform_crv = "noseSneerLeft_ctrl"
crv_attr = "translateY"
blendshape_end = -1.0
crv_end = -1.0
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "eyeLookOutLeft"
transform_crv = "eyeLook_left_ctrl"
crv_attr = "translateX"
mirror_right = true
mirror_right_invert = true  # inverts crv_end value

[[setdrivenkeys]]
blendshape_attr = "eyeLookInLeft"
transform_crv = "eyeLook_left_ctrl"
crv_attr = "translateX"
crv_end = -1.0
mirror_right = true
mirror_right_invert = true

[[setdrivenkeys]]
blendshape_attr = "eyeLookUpLeft"
transform_crv = "eyeLook_left_ctrl"
crv_attr = "translateY"
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "eyeLookDownLeft"
transform_crv = "eyeLook_left_ctrl"
crv_attr = "translateY"
crv_end = -1.0
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "jawOpen"
transform_crv = "jawOpen_ctrl"
crv_attr = "translateY"
crv_end = -1.0

[[setdrivenkeys]]
blendshape_attr = "jawLeft"
transform_crv = "jawOpen_ctrl"
crv_attr = "translateX"
blendshape_end = 1.0
crv_end = 1.0

[[setdrivenkeys]]
blendshape_attr = "jawRight"
transform_crv = "jawOpen_ctrl"
crv_attr = "translateX"
blendshape_end = 1.0
crv_end = -1.0

[[setdrivenkeys]]
blendshape_attr = "browInnerUp"
transform_crv = "browInnerUp_ctrl"
crv_attr = "translateY"

[[setdrivenkeys]]
blendshape_attr = "browInnerUp"
transform_crv = "browInnerUp_ctrl"
crv_attr = "translateY"
blendshape_end = -1.0
crv_end = -1.0

[[setdrivenkeys]]
blendshape_attr = "browOuterUpLeft"
transform_crv = "browUpDown_left_ctrl"
crv_attr = "translateY"
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "browDownLeft"
transform_crv = "browUpDown_left_ctrl"
crv_attr = "translateY"
crv_end = -1.0
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "tongueOut"
transform_crv = "tongueOut_ctrl"
crv_attr = "translateY"

[[setdrivenkeys]]
blendshape_attr = "cheekSquintLeft"
transform_crv = "cheekSquintLeft_ctrl"
crv_attr = "translateY"
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "cheekSquintLeft"
transform_crv = "cheekSquintLeft_ctrl"
crv_attr = "translateY"
blendshape_end = -1.0
crv_end = -1.0
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "cheekPuff"
transform_crv = "cheekPuff_ctrl"
crv_attr = "translateY"

[[setdrivenkeys]]
blendshape_attr = "cheekPuff"
transform_crv = "cheekPuff_ctrl"
crv_attr = "translateY"
blendshape_end = -1.0
crv_end = -1.0

[[setdrivenkeys]]
blendshape_attr = "eyeWideLeft"
transform_crv = "eyeWideBlink_left_ctrl"
crv_attr = "translateY"
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "eyeBlinkLeft"
transform_crv = "eyeWideBlink_left_ctrl"
crv_attr = "translateY"
crv_end = -1.0
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "eyeSquintLeft"
transform_crv = "eyeSquintLeft_ctrl"
crv_attr = "translateY"
crv_end = -1.0
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "jawForward"
transform_crv = "jawForward_ctrl"
crv_attr = "translateY"

[[setdrivenkeys]]
blendshape_attr = "mouthClose"
transform_crv = "mouthClose_ctrl"
crv_attr = "translateY"
crv_end = -1.0

[[setdrivenkeys]]
blendshape_attr = "mouthFunnel"
transform_crv = "mouthFunnel_ctrl"
crv_attr = "translateY"

[[setdrivenkeys]]
blendshape_attr = "mouthPucker"
transform_crv = "mouthPucker_ctrl"
crv_attr = "translateY"

[[setdrivenkeys]]
blendshape_attr = "mouthLeft"
transform_crv = "mouthLeft_ctrl"
crv_attr = "translateX"
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "mouthSmileLeft"
transform_crv = "mouthSmileLeft_ctrl"
crv_attr = "translateX"
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "mouthFrownLeft"
transform_crv = "mouthFrownLeft_ctrl"
crv_attr = "translateX"
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "mouthDimpleLeft"
transform_crv = "mouthDimpleLeft_ctrl"
crv_attr = "translateX"
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "mouthStretchLeft"
transform_crv = "mouthStretchLeft_ctrl"
crv_attr = "translateX"
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "mouthPressLeft"
transform_crv = "mouthPressLeft_ctrl"
crv_attr = "translateX"
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "mouthRollLower"
transform_crv = "mouthRollLower_ctrl"
crv_attr = "translateY"

[[setdrivenkeys]]
blendshape_attr = "mouthRollUpper"
transform_crv = "mouthRollUpper_ctrl"
crv_attr = "translateY"

[[setdrivenkeys]]
blendshape_attr = "mouthShrugLower"
transform_crv = "mouthShrugLower_ctrl"
crv_attr = "translateY"

[[setdrivenkeys]]
blendshape_attr = "mouthShrugUpper"
transform_crv = "mouthShrugUpper_ctrl"
crv_attr = "translateY"

[[setdrivenkeys]]
blendshape_attr = "mouthLowerDownLeft"
transform_crv = "mouthLowerDownLeft_ctrl"
crv_attr = "translateY"
mirror_right = true

[[setdrivenkeys]]
blendshape_attr = "mouthUpperUpLeft"
transform_crv = "mouthUpperUpLeft_ctrl"
crv_attr = "translateY"
mirror_right = true
