# fk_ik_spline_chain_mod: Creates a blended fk ik spline rig module. 
    # An fk ik chain, where ik ctrls are driven by a spline curve.

[[rig_module]]
rig_module = "fk_ik_spline_chain_mod" 
rig_module_name = "spine" 
joints = "spine_01, spine_04"
get_joint_chain = true

# ----- base -----
[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "root" 
joints = "root"

[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "pelvis" 
joints = "pelvis"
