# ---------- main ----------
[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "root" 
joints = "root"

[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "pelvis" 
joints = "pelvis"

[[rig_module]]
rig_module = "fk_chain_mod" 
rig_module_name = "spine" 
joints = "spine_01, spine_04"
get_joint_chain = true

[[rig_module]]
rig_module = "fk_chain_mod" 
rig_module_name = "leg" 
joints = "thigh_l, calf_l, foot_l, ball_l"
mirror_direction = "left"
mirror_right = true

# ---------- ezor skirt ----------
[[rig_module]]
rig_module = "flexi_surface_ik_chain_mod" 
rig_module_name = "ezorLeatherStrip" 
mirror_direction = "left"
mirror_right = true
joint_chains = [  # add start, or start and end joints for each chain
    "ezorLeatherStrip_left_a01_jnt",
    "ezorLeatherStrip_left_b01_jnt",
    "ezorLeatherStrip_left_c01_jnt",
    "ezorLeatherStrip_left_d01_jnt",
    "ezorLeatherStrip_left_e01_jnt",
    "ezorLeatherStrip_left_f01_jnt",
    "ezorLeatherStrip_left_g01_jnt",
    "ezorLeatherStrip_left_h01_jnt",
]
flexi_surface = "flexiSurface_geo"
hide_end_ctrl = true

[[rig_module]]
rig_module = "fk_control_mod" 
rig_module_name = "ezorLeatherStripOffset" 
mirror_direction = "left" 
joints = "flexiSurfaceOffset_frontLeft_jnt, flexiSurfaceOffset_outerLeft_jnt, flexiSurfaceOffset_backLeft_jnt"
use_joint_names = true
mirror_right = true

